name: GitHub-Profile-Summary-Cards

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    permissions:
      contents: write
    # Forzamos Node 24 para estar al día con el cambio de junio
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - uses: actions/checkout@v4 # Actualizado a v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: Ian-M-09
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
