name: GitHub-Profile-Summary-Cards

on:
  schedule: # Se ejecutará automáticamente cada 24 horas
    - cron: "0 */12 * * *"
  workflow_dispatch: # Te permite ejecutarlo manualmente cuando quieras

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          github_user_name: Ian-M-09
          updated_at: true
          # Elegimos el tema dark para que combine con tus capturas anteriores
          theme: dark
